version: '2'
services:
  web:
    restart: always
    image: mean-demo:0.0.1
    ports:
     - "8080:80"
     - "4200:4200"
     - "3000:3000"
     - "2222:2222"
    environment:
     - MONGODB_URI=mongodb://db:27017/mean
    depends_on:
     - db
  db:
    image: mongo:latest
    restart: always
    volumes_from:
      - db-data
  db-data:
    image: mongo:latest
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true

